server:
  port: 8090

spring:
  application:
    name: download
  profiles:
    active: dev
  ####  \u914D\u7F6E\u6570\u636E\u5E93\u76F8\u5173   url: jdbc:sqlserver://10.2.0.201:1433;DatabaseName=lisdb_new
  datasource:
    ##url: jdbc:sqlserver://10.2.0.204:1433;DatabaseName=hecdb_fk_2021
    url: jdbc:sqlserver://10.2.0.201:1433;DatabaseName=lisdb_new
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Fmso551
    druid:
      initial-size: 5
      max-active: 200
      min-idle: 1
      max-wait: 10
      validation-query: select 'x'


thymeleaf:
  cache: false
  prefix: classpath:/templates/
  mode: LEGACYHTML5


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
